name: quiz
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  postgrest: ^2.4.0
  supabase_flutter: ^2.8.2
  image_picker: ^0.8.7+4
  file_picker: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/signup_image.png
    - assets/login_image.png
            
